version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/aldi-f/kube-disk-stats
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
